// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GridFormController from "./grid_form_controller"
application.register("grid-form", GridFormController)

import GridSubscriptionController from "./grid_subscription_controller"
application.register("grid-subscription", GridSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
